version: '3.1'
services:
  ypstudio-dev:
    container_name: ypstudio-dev
    image: registry.gitlab.com/airp0wer/ypstudio-nextjs:dev
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ypstudio-dev.rule=Host(`dev.ypstudio.ru`)"
      - "traefik.http.routers.ypstudio-dev.entrypoints=websecure"
      - "traefik.http.services.ypstudio-dev.loadbalancer.server.port=3000"
      - "traefik.http.routers.ypstudio-dev.tls.certresolver=myresolver"
    networks:
      - traefik
networks:
  traefik:
    name: traefik



