# Use root/example as user/password credentials
version: '3.1'
services:
  ypstudio:
    container_name: ypstudio
    image: docker.io/library/ypstudio-nextjs
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ypstudio.rule=Host(`ypstudio.ru`)"
      - "traefik.http.routers.ypstudio.entrypoints=websecure"
      - "traefik.http.services.ypstudio.loadbalancer.server.port=3000"
      - "traefik.http.routers.ypstudio.tls.certresolver=myresolver"
      #- "traefik.http.services.ypstudio.loadbalancer.healthcheck.path=/"
      #- "traefik.http.services.ypstudio.loadbalancer.healthcheck.interval=5s"
      #- "traefik.http.services.ypstudio.loadbalancer.healthcheck.timeout=1s"
      # - "traefik.http.services.ypstudio.loadbalancer.healthcheck.scheme=http"
    networks:
      - traefik
  mongo:
    container_name: mongo-airp0wer-server
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - 'mongodata:/data/db'
      - 'mongodata:/data/configdb'
    networks:
      - traefik
  mongo-express:
    container_name: mongo-airp0wer-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-airp0wer-server
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    volumes:
      - 'mongodata:/data/db'
    networks:
      - traefik
networks:
  traefik:
    name: traefik
volumes:
  mongodata:
    name: mongodb-init-docker_mongodata



